<?php

namespace Sdz\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{

	public function myFindOne($nom)
	{
	  // On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
	  $qb = $this->_em->createQueryBuilder();

	  $qb->select('c')
	     ->from('SdzBlogBundle:Categorie', 'c')
	     ->where('c.nom = :nom')
	     ->setParameter('nom', $nom);

	    return $qb->getQuery()
	              ->getResult();
	}
}
